// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_Abdelrhman_khaled_0522015_S4.Data;

#nullable disable

namespace WebApi_Abdelrhman_khaled_0522015_S4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241120083532_quiz")]
    partial class quiz
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.Property<int>("directorsId")
                        .HasColumnType("int");

                    b.HasKey("MoviesId", "directorsId");

                    b.HasIndex("directorsId");

                    b.ToTable("DirectorMovie");
                });

            modelBuilder.Entity("WebApi_Abdelrhman_khaled_0522015_S4.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("WebApi_Abdelrhman_khaled_0522015_S4.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("WebApi_Abdelrhman_khaled_0522015_S4.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("releaseyear")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("WebApi_Abdelrhman_khaled_0522015_S4.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_director")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_director")
                        .IsUnique();

                    b.ToTable("nationalities");
                });

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.HasOne("WebApi_Abdelrhman_khaled_0522015_S4.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi_Abdelrhman_khaled_0522015_S4.Models.Director", null)
                        .WithMany()
                        .HasForeignKey("directorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi_Abdelrhman_khaled_0522015_S4.Models.Movie", b =>
                {
                    b.HasOne("WebApi_Abdelrhman_khaled_0522015_S4.Models.Category", "Category")
                        .WithMany("movies")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApi_Abdelrhman_khaled_0522015_S4.Models.Nationality", b =>
                {
                    b.HasOne("WebApi_Abdelrhman_khaled_0522015_S4.Models.Director", "director")
                        .WithOne("nationality")
                        .HasForeignKey("WebApi_Abdelrhman_khaled_0522015_S4.Models.Nationality", "id_director")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("director");
                });

            modelBuilder.Entity("WebApi_Abdelrhman_khaled_0522015_S4.Models.Category", b =>
                {
                    b.Navigation("movies");
                });

            modelBuilder.Entity("WebApi_Abdelrhman_khaled_0522015_S4.Models.Director", b =>
                {
                    b.Navigation("nationality");
                });
#pragma warning restore 612, 618
        }
    }
}
